# 开发环境
spring:
  application:
    name: issacmsc-consumer-depart
  profiles: dev

server:
  port: 7070

eureka:
  client:
    # 指定 Eureka 注册中心
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka
  instance:
    instance-id: issac-msc-consumer-7070

# 开启 Feign 对 Hystrix 支持
feign:
  hystrix:
    enabled: true

# 设置服务熔断时限，默认5000毫秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

---
# 测试环境
spring:
  application:
    name: issacmsc-consumer-depart
  profiles: test

server:
  port: 9090

eureka:
  client:
    # 指定 Eureka 注册中心
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka
  instance:
    instance-id: issac-msc-consumer-9090

# 开启 Feign 对 Hystrix 支持
feign:
  hystrix:
    enabled: true

# 设置服务熔断时限，默认5000毫秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
